/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Librarian;

import AppSys.Business;
import Branch.Branch;
import Branch.UserAccount;
import Library.Author;
import Library.AuthorDirectory;
import Library.Genre;
import Library.Library;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author narot
 */
public class AddAuthorJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount useraccount;
    Branch branch;
    DefaultTableModel tableModel1;
    DefaultTableModel tableModel2;
    /**
     * Creates new form AddAuthorJPanel
     */
    public AddAuthorJPanel() {
        initComponents();
    }
    
    public AddAuthorJPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel1 = (DefaultTableModel) jAuthorTable.getModel();
        this.tableModel2 = (DefaultTableModel) jGenreTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFieldAuthor = new javax.swing.JTextField();
        AddAuthorBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAuthorTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jFieldGenre = new javax.swing.JTextField();
        AddGenreBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jGenreTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Author");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 33, 163, -1));
        add(jFieldAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 102, 103, -1));

        AddAuthorBtn.setText("Add Author");
        AddAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAuthorBtnActionPerformed(evt);
            }
        });
        add(AddAuthorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 165, 103, -1));

        jLabel2.setText("Enter Author: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 105, -1, -1));

        jAuthorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Author"
            }
        ));
        jScrollPane1.setViewportView(jAuthorTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 233, 245, 183));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Genre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 39, 163, -1));
        add(jFieldGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 96, 103, -1));

        AddGenreBtn.setText("Add Genre");
        AddGenreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenreBtnActionPerformed(evt);
            }
        });
        add(AddGenreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 162, 103, -1));

        jLabel4.setText("Enter Genre: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 99, -1, -1));

        jGenreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Genre"
            }
        ));
        jScrollPane2.setViewportView(jGenreTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 233, 266, 183));
    }// </editor-fold>//GEN-END:initComponents

    private void AddAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAuthorBtnActionPerformed
        // TODO add your handling code here:
        Library lib = this.business.getBranch().getLibrary();
        if(lib.getAuthors().findAuthor(jFieldAuthor.getText()) == null){
            Author a = this.business.getBranch().getLibrary().getAuthors().AddAuthor(jFieldAuthor.getText());
            populateAuthorTable();
        } else {
            JOptionPane.showMessageDialog(null, "Author already exist!");
        }
    }//GEN-LAST:event_AddAuthorBtnActionPerformed

    private void AddGenreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenreBtnActionPerformed
        // TODO add your handling code here:
        Library lib = this.business.getBranch().getLibrary();
        if(lib.getGenres().findGenre(jFieldAuthor.getText()) == null){
            Genre g = this.business.getBranch().getLibrary().getGenres().createGenre(jFieldAuthor.getText());
            populateGenreTable();
        } else {
            JOptionPane.showMessageDialog(null, "Genre already exist!");
        }
    }//GEN-LAST:event_AddGenreBtnActionPerformed

    public void populateAuthorTable(){
        
        tableModel1.setRowCount(0);
        for(Author a: this.business.getBranch().getLibrary().getAuthors().getAuthors()){
            Author au = this.business.getBranch().getLibrary().getAuthors().findAuthor(a.getAuthor());
            Object[] row = new Object[1];
            row[0] = au.getAuthor();
            tableModel1.addRow(row);
        }
    }
    
    public void populateGenreTable() {
        tableModel2.setRowCount(0);
        for(Genre g: this.business.getBranch().getLibrary().getGenres().getGenreList()){
            Genre ge = this.business.getBranch().getLibrary().getGenres().findGenre(g.getGenre());
            Object[] row = new Object[1];
            row[0] = ge.getGenre();
            tableModel1.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAuthorBtn;
    private javax.swing.JButton AddGenreBtn;
    private javax.swing.JTable jAuthorTable;
    private javax.swing.JTextField jFieldAuthor;
    private javax.swing.JTextField jFieldGenre;
    private javax.swing.JTable jGenreTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
