/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Librarian;

import AppSys.Business;
import Branch.Branch;
import Branch.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author narot
 */
public class BookIssueRequestJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount useraccount;
    Branch branch;
    DefaultTableModel tableModel1;
    /**
     * Creates new form BookIssueRequestJPanel
     */
    public BookIssueRequestJPanel() {
        initComponents();
    }

    public BookIssueRequestJPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel1 = (DefaultTableModel) jBookIssueTable.getModel();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBookIssueTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Issue Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 27, 191, -1));

        jBookIssueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RentalID", "Price", "Type", "RentDuration", "Status"
            }
        ));
        jScrollPane1.setViewportView(jBookIssueTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 88, 627, 199));

        jButton1.setText("Accept Issue");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 330, -1, -1));

        jButton2.setText("Reject Issue");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 330, -1, -1));

        jButton3.setText("Issue Returned");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jBookIssueTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
