/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import AppSys.Business;
import Branch.Branch;
import Branch.UserAccount;
import Branch.UserAccountDirectory;
import Employee.Employee;
import Library.Library;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author narot
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount useraccount;
    Branch branch;
    DefaultTableModel tableModel;
    /**
     * Creates new form AddEmployeeJPanel
     */
    public AddEmployeeJPanel() {
        initComponents();
    }
    
    public AddEmployeeJPanel(Business business, UserAccount useraccount) {
        initComponents();
        
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jEmployeeTable.getModel();
        this.branch = business.getBranch();
        
        showBranches();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldPwd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        FieldExprience = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEmployeeTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        showBranches = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 32, 163, -1));

        jLabel2.setText("Enter Password:  ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 134, 108, -1));
        add(fieldPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 131, 162, -1));

        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 249, -1, 32));

        FieldExprience.setToolTipText("");
        add(FieldExprience, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 159, 162, -1));

        jLabel3.setText("Enter Exprience: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 162, 108, -1));

        jLabel4.setText("Select Designation: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 187, 108, -1));

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Librarian", "Branch Manager" }));
        add(jComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 187, 162, -1));

        jEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Username", "Password", "Exprience", "Designation", "Branch"
            }
        ));
        jScrollPane1.setViewportView(jEmployeeTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 342, 520, 210));

        jLabel5.setText("Enter Employee Username: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 106, 152, -1));
        add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 103, 162, -1));

        jLabel6.setText("Select Branch: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 215, 108, -1));

        showBranches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(showBranches, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 215, 162, -1));

        jLabel7.setText("Enter Employee Name: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 78, 152, -1));
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 75, 162, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory ua = this.business.getBranch().getBranchuseraccountDirectory();
        String branch = (String) showBranches.getSelectedItem();
        String branchValue = showBranches.getSelectedItem().toString();
        //String Role = (String) jComboBoxRole.getSelectedItem();
        String roleValue = jComboBoxRole.getSelectedItem().toString();
   
        if(!this.branch.branchExists(branch)){
            JOptionPane.showMessageDialog(null, "Branch does not exist!");
        }
        else if(ua.authenticateUser(fieldUsername.getText(), fieldPwd.getText(), roleValue) != null) {
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken");
        }
//        else if(ua.authenticateEmployeeUnique(roleValue, branchValue) != null) {
//            JOptionPane.showMessageDialog(null, "Sorry One "+ roleValue + " already Exists!" );
//        }
        else{
            // save the customer obj for user and useraccount credentials
            UserAccount user = this.business.getBranch().getBranchuseraccountDirectory().createUserAccount(fieldUsername.getText(), fieldPwd.getText(), roleValue, branchValue);
            this.business.getBranch().getLibrary().getEd().createEmployee(user.getAccountId(), fieldName.getText(), Integer.valueOf(FieldExprience.getText()), roleValue );
            
            fieldUsername.setText("");
            fieldPwd.setText("");
            fieldName.setText("");
            FieldExprience.setText("");
            showBranches.setSelectedIndex(0);
            jComboBoxRole.setSelectedIndex(0);
        }
        populateTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showBranches() {
        showBranches.removeAllItems();

        for (Library lib : this.business.getBranch().getBranches()){
            showBranches.addItem(String.valueOf(lib));
        }
    }
    
    public void populateTable() {
        
        tableModel.setRowCount(0);
        for(Employee c: this.business.getBranch().getLibrary().getEd().getEmployees()) {
            UserAccount u = this.business.getBranch().getBranchuseraccountDirectory().findById(c.getPersonID());
            
            Object[] row = new Object[7];
            
            row[0] = c.getPersonID();
            row[1] = c.getName();
            row[2] = u.getUsername();
            row[3] = u.getPassword();
            row[4] = c.getExprience();
            row[5] = u.getRole();
            row[6] = u.getBranch();
            
            tableModel.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldExprience;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPwd;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JTable jEmployeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> showBranches;
    // End of variables declaration//GEN-END:variables
}
