/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.Person;
import model.Contact;
import model.Reciepe;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nishant
 */
public class viewJPanel extends javax.swing.JPanel {
private Person person;

    /**
     * Creates new form View
     */
    public viewJPanel() {
        initComponents();
    }

    viewJPanel(Person personreceipe) {
        initComponents();
        this.person = personreceipe;
        
        display();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblview = new javax.swing.JTable();

        tblview.setBackground(new java.awt.Color(235, 244, 245));
        tblview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cheaf's First Name", "Chef's Last Name", "User Name", "Email.ID", "Contact No.", "Reciepe Title", "Image", "No. of Servings", "Diff Level", "Is Gluten Free", "FoodCatagory", "Description"
            }
        ));
        tblview.setShowGrid(true);
        tblview.setShowHorizontalLines(true);
        tblview.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblview);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1362, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void display(){
    DefaultTableModel model= (DefaultTableModel )tblview.getModel();
    model.setRowCount(0);
       for(Reciepe  io : person.getReciepelist()){
            Object[]row =new Object[12];
            row[0]=io;
            row[1]=person.getLastName();
            row[2]=person.getUserName();
            row[3]=person.getContact().getEmailID();
            row[4]=person.getContact().getPhoneNo();
            row[5]= io.getTitle();
            row[6]= io.getPic();
            row[7]= io.getNoServings();
            row[8]= io.getDiffLevel();
            row[9]= io.isGlutenFree();
            row[10]= io.getCategoryFood();
            row[11]=io.getDescript();
            model.addRow(row);
       
            
            
       }      
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblview;
    // End of variables declaration//GEN-END:variables
}
