/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Applicant;
import Model.ApplicantCatalog;
import Model.Business;
import Model.Insurance;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nishn 
 */
public class AssignInsurancePanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignInsurancePanel
     */
    private Business business;
    
    public AssignInsurancePanel() {
        initComponents();
    }
    
    AssignInsurancePanel(Business business) {
        initComponents();
        
        this.business = business;
        
        populateDropdowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                petBox = new javax.swing.JComboBox();
                planBox = new javax.swing.JComboBox();
                assignBtn = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(204, 204, 255));

                planBox.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                planBoxItemStateChanged(evt);
                        }
                });

                assignBtn.setText("ASSIGN INSURANCE PLAN TO PET");
                assignBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                assignBtnActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("Assign Insurance");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(petBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(127, 127, 127)
                                                .addComponent(planBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(257, 257, 257)
                                                .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(269, 269, 269)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(119, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(planBox)
                                        .addComponent(petBox))
                                .addGap(56, 56, 56)
                                .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(317, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    
    public void populateDropdowns(){
        ArrayList<Insurance> insurancePlans = this.business.getInsuranceDetail().getPlanDetails();
        
        ArrayList<Applicant> applicants = this.business.getApplicantCatalog().getApplicants();
        
        for(Applicant app : applicants){
            petBox.addItem(app);
        }
        
        for(Insurance in : insurancePlans){
            planBox.addItem(in);
        }
    }
    
    private void planBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_planBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_planBoxItemStateChanged

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        
        Applicant app = (Applicant) petBox.getSelectedItem();
        Insurance in = (Insurance) planBox.getSelectedItem();
        app.setInsurancePlan_assignment(in);

        JOptionPane.showMessageDialog(null, "Successfully Assigned Insurance Plan to Applicant!");
        
    }//GEN-LAST:event_assignBtnActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton assignBtn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JComboBox petBox;
        private javax.swing.JComboBox planBox;
        // End of variables declaration//GEN-END:variables
}
