/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Applicant;
import Model.ApplicantCatalog;
import Model.Business;
import Model.Vaccine;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shalomdaniel
 */
public class CreatePanel extends javax.swing.JPanel {

    private Business business;

    /**
     * Creates new form CreatePanel
     */
    public CreatePanel() {
        initComponents();
    }
    
    CreatePanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldAppID = new javax.swing.JTextField();
        fieldOwnerFirstname = new javax.swing.JTextField();
        fieldOwnerLastName = new javax.swing.JTextField();
        CreateDetailsBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldPetAge = new javax.swing.JTextField();
        fieldPetName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldPetBreed = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldPetVaccine = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        typeComboBox = new javax.swing.JComboBox<>();
        fieldNoOfVax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jLabel2.setText("Enter Applicant ID");

        jLabel3.setText("Enter Application Date");

        jLabel4.setText("Enter Owner First Name");

        jLabel5.setText("Enter Owner Last Name");

        fieldAppID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldAppIDFocusLost(evt);
            }
        });
        fieldAppID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAppIDActionPerformed(evt);
            }
        });

        fieldOwnerFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOwnerFirstnameActionPerformed(evt);
            }
        });

        fieldOwnerLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOwnerLastNameActionPerformed(evt);
            }
        });

        CreateDetailsBtn.setText("ADD DETAILS");
        CreateDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDetailsBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Pet Age");

        jLabel7.setText("Enter Pet Name");

        fieldPetAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPetAgeActionPerformed(evt);
            }
        });

        fieldPetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPetNameActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Pet Gender");

        jLabel9.setText("Enter Pet Type");

        fieldPetBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPetBreedActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter Pet Breed");

        jLabel11.setText("Is Vaccination Course completed ?");

        fieldPetVaccine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPetVaccineFocusGained(evt);
            }
        });
        fieldPetVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPetVaccineActionPerformed(evt);
            }
        });

        jLabel12.setText("Enter Pet Vaccine Details");

        jDateChooser2.setDateFormatString("dd-MM-yyyy");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat" }));

        fieldNoOfVax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNoOfVaxFocusGained(evt);
            }
        });
        fieldNoOfVax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoOfVaxActionPerformed(evt);
            }
        });

        jLabel13.setText("Number of Vaccines taken  -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldPetVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldNoOfVax, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(CreateDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldPetBreed)
                                .addComponent(fieldOwnerFirstname)
                                .addComponent(fieldOwnerLastName)
                                .addComponent(fieldAppID)
                                .addComponent(fieldPetName)
                                .addComponent(fieldPetAge)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAppID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldOwnerFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPetAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPetBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPetVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNoOfVax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(CreateDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAppIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAppIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAppIDActionPerformed

    private void fieldOwnerFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOwnerFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOwnerFirstnameActionPerformed

    private void fieldOwnerLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOwnerLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOwnerLastNameActionPerformed

    private void CreateDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDetailsBtnActionPerformed
        // TODO add your handling code here:
        
        String petVaccineCourseStatus;
        ApplicantCatalog appCatalog = this.business.getApplicantCatalog();
        
        String appID = fieldAppID.getText();
        String firstname = fieldOwnerFirstname.getText();
        String lastname = fieldOwnerLastName.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String app_date = sdf.format(jDateChooser2.getDate());
        
//        System.out.println(app_date);
        
        String petType = typeComboBox.getSelectedItem().toString();
        String petname = fieldPetName.getText();
        String petBreed = fieldPetBreed.getText();
        String petGender = jComboBox1.getSelectedItem().toString();
        
//        System.out.println(petGender);
        
        String petAge = fieldPetAge.getText();
        
        String petVaccine = fieldPetVaccine.getText();
        if(petVaccine.isEmpty()){
            fieldNoOfVax.setText(String.valueOf(0));
        }else{
            String[] values = petVaccine.split(",");
            fieldNoOfVax.setText(String.valueOf(values.length));      
        }
        
//        System.out.println("value is" + fieldNoOfVax.getText());


        if (jCheckBox1.isSelected()) {
            petVaccineCourseStatus = "Yes";
        } else {
            petVaccineCourseStatus = "No";
        } 

        ArrayList<JTextField> textFields = new ArrayList<JTextField>();
        textFields.add(fieldAppID);
        textFields.add(fieldOwnerFirstname);
        textFields.add(fieldOwnerLastName);
        textFields.add(fieldPetAge);
        textFields.add(fieldPetBreed);
        textFields.add(fieldPetName);
        
        boolean allFieldsFilled = true;

        for (JTextField textField : textFields) {
            if(textField.getText().isEmpty()){
                allFieldsFilled = false;
                break;
            }
        }
        
        if(allFieldsFilled){
   
            appCatalog.createApplicant(firstname, lastname, Integer.valueOf(appID), petname, petType, petBreed, petGender, Integer.valueOf(petAge), petVaccine, petVaccineCourseStatus, app_date);

            JOptionPane.showMessageDialog(null, "Successfully added Applicant to Catalog");  
  
            fieldAppID.setText("");
            fieldOwnerFirstname.setText("");
            fieldOwnerLastName.setText("");

            typeComboBox.setSelectedItem(null);
            fieldPetName.setText("");
            fieldPetBreed.setText("");
            jComboBox1.setSelectedItem(null);
            fieldPetAge.setText("");
            jDateChooser2.setDate(null);
            fieldNoOfVax.setText("");

            fieldPetVaccine.setText("");
            jCheckBox1.setSelected(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Fields cannot be empty! ");  
        }
        
        
    }//GEN-LAST:event_CreateDetailsBtnActionPerformed

    private void fieldPetAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPetAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPetAgeActionPerformed

    private void fieldPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPetNameActionPerformed

    private void fieldPetBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPetBreedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPetBreedActionPerformed

    private void fieldPetVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPetVaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPetVaccineActionPerformed

    private void fieldNoOfVaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoOfVaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoOfVaxActionPerformed

    private void fieldPetVaccineFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPetVaccineFocusGained
        // TODO add your handling code here:
        fieldPetVaccine.setText(null);
    }//GEN-LAST:event_fieldPetVaccineFocusGained

    private void fieldNoOfVaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNoOfVaxFocusGained
        // TODO add your handling code here:
        fieldNoOfVax.setText(null);
    }//GEN-LAST:event_fieldNoOfVaxFocusGained

    private void fieldAppIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldAppIDFocusLost
        // TODO add your handling code here:
        
        ApplicantCatalog appCatalog = this.business.getApplicantCatalog();
        
        if (fieldAppID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter some text!");
            fieldAppID.requestFocus();
        }   
        
        if(appCatalog.checkApplicationIDUnique(Integer.valueOf(fieldAppID.getText())) == false){
            JOptionPane.showMessageDialog(null, "Application ID is already taken. Please enter unique ID!");
            fieldAppID.setText("");
            fieldAppID.requestFocus();
        }     
        
        
    }//GEN-LAST:event_fieldAppIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateDetailsBtn;
    private javax.swing.JTextField fieldAppID;
    private javax.swing.JTextField fieldNoOfVax;
    private javax.swing.JTextField fieldOwnerFirstname;
    private javax.swing.JTextField fieldOwnerLastName;
    private javax.swing.JTextField fieldPetAge;
    private javax.swing.JTextField fieldPetBreed;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPetVaccine;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables
}
