/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.ApplicantCatalog;
import Model.Business;
import Model.Insurance;
import Model.PlanDetail;
import javax.swing.JOptionPane;

/**
 *
 * @author shalomdaniel
 */
public class CreateInsurancePlans extends javax.swing.JPanel {

    private Business business;
    Insurance insurance = new Insurance();

    /**
     * Creates new form CreateInsurancePlans
     */
    public CreateInsurancePlans() {
        initComponents();
    }

    CreateInsurancePlans(Business business) {
        initComponents();
        this.business = business;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldInsurancePlanName = new javax.swing.JTextField();
        fieldCostPA = new javax.swing.JTextField();
        fieldCostPM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldInsurancePLanID = new javax.swing.JTextField();
        addPlanBtn = new javax.swing.JButton();

        jLabel3.setText("Insurance Plan Cost per Annum");

        jLabel5.setText("Enter Insurance Plan Cost Per Month");

        fieldInsurancePlanName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInsurancePlanNameActionPerformed(evt);
            }
        });

        fieldCostPA.setEnabled(false);
        fieldCostPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCostPAActionPerformed(evt);
            }
        });

        fieldCostPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCostPMActionPerformed(evt);
            }
        });
        fieldCostPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldCostPMKeyTyped(evt);
            }
        });

        jLabel2.setText("Enter Insurance Plan Name");

        jLabel6.setText("Enter Insurance Plan ID");

        fieldInsurancePLanID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldInsurancePLanIDFocusLost(evt);
            }
        });
        fieldInsurancePLanID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInsurancePLanIDActionPerformed(evt);
            }
        });

        addPlanBtn.setText("ADD INSURANCE PLAN TO SYSTEM");
        addPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldInsurancePLanID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldInsurancePlanName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCostPM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCostPA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(addPlanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsurancePLanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInsurancePlanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCostPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCostPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(addPlanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldInsurancePlanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInsurancePlanNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldInsurancePlanNameActionPerformed

    private void fieldCostPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCostPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCostPAActionPerformed

    private void fieldCostPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCostPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCostPMActionPerformed

    private void fieldInsurancePLanIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInsurancePLanIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldInsurancePLanIDActionPerformed

    private void addPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlanBtnActionPerformed
        // TODO add your handling code here:
        PlanDetail planCatalog = this.business.getInsuranceDetail();
        
        String planID = String.valueOf(fieldInsurancePLanID.getText());
        String planName = fieldInsurancePlanName.getText();
        String planCostpm = String.valueOf(fieldCostPM.getText());
        
        String planCostpa = String.valueOf(insurance.calulatePlanCostPerAnnum(Double.valueOf(fieldCostPM.getText())));
        fieldCostPA.setText(planCostpa);
        
        planCatalog.createInsurancePlan(Integer.valueOf(planID), planName, Double.valueOf(planCostpm));
        
        JOptionPane.showMessageDialog(null, "Successfully added Insurance Plan to System!");
        
        fieldInsurancePlanName.setText("");
        fieldInsurancePLanID.setText("");
        fieldCostPM.setText("");     
        fieldCostPA.setText("");
    }//GEN-LAST:event_addPlanBtnActionPerformed

    private void fieldCostPMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCostPMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCostPMKeyTyped

    private void fieldInsurancePLanIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldInsurancePLanIDFocusLost
        // TODO add your handling code here:
      
        PlanDetail planCatalog = this.business.getInsuranceDetail();
        
        if(planCatalog.checkInsuranceIDUnique(Integer.valueOf(fieldInsurancePLanID.getText())) == false){
            JOptionPane.showMessageDialog(null, "Application ID is already taken. Please enter unique ID!");
            fieldInsurancePLanID.setText("");
            fieldInsurancePLanID.requestFocus();
        }     
        
    }//GEN-LAST:event_fieldInsurancePLanIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlanBtn;
    private javax.swing.JTextField fieldCostPA;
    private javax.swing.JTextField fieldCostPM;
    private javax.swing.JTextField fieldInsurancePLanID;
    private javax.swing.JTextField fieldInsurancePlanName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
